openapi: 3.0.0
info:
  description: scigateway authentication api
  title: scigateway-auth
  version: '0'
servers:
- url: http://localhost:5050
paths:
  /verify:
    post:
      requestBody:
          description: The JWT that is to be verified by the api.
          required: true
          content:
            application/json:
              schema:
                type: object
              example:
                token: xxxxx.yyyyy.zzzzz
      responses:
        '400':
          description: When a bad request is sent
        '401':
          description: When no post body is sent
        '403':
          description: When the token is not valid
        '200':
          description: When the token is valid
  /login:
    post:
      requestBody:
        description: The mnemonic and credentials to be used to login and obtain a session
        required: true
        content:
          application/json:
            schema:
              type: object
            example:
              mnemonic: uows
              credentials:
                - username: user
                - password: password
      responses:
        '400':
          description: When a bad request is sent
        '401':
          description: When no post body is sent
        '200':
          description: A JWT
        '403':
          description: When bad credentials are provided
        